import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
<<<<<<< HEAD
import Home from './src/pages';
import Tabitem from '@theme/TabItem';
=======

>>>>>>> 4bfef3160ef04643058a5ba9a73fe89ef9467790
// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
<<<<<<< HEAD
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually
  
  destruccionSidebar: [
    'Aplicaciones/Destruccion de equipos/intro',
    {
      type: 'category',
      label: 'Destruccion de Equipos',
      collapsible:true,
      items:[
        {
      type:'autogenerated',
      dirName:'Aplicaciones/Destruccion de equipos',
    },
    ],
    },
  ],

  discoduroSidebar: [
    
    {
      type: 'category',
      label: 'Discos Duros Inventario',
      collapsible:true,
      items:[
        {
      type:'autogenerated',
      dirName:'Aplicaciones/Discos Duros',
    },
    ],
    },
  ],

  tableauSidebar: [
    
    {
      type: 'category',
      label: 'Tableau',
      collapsible:true,
      items:[
        {
      type:'autogenerated',
      dirName:'Aplicaciones/Tableau',
    },
    ],
    },
  ],

  nuevoIngresoSidebar: [
    
   {
      type: 'category',
      label: 'Tableau',
      collapsible:true,
      items:[
        {
      type:'autogenerated',
      dirName:'Aplicaciones/Nuevo ingreso',
    },
    ],
    },
  ],

   nuevoEquipoSidebar: [
    
   {
      type: 'category',
      label: 'Nuevo Inventario',
      collapsible:true,
      items:[
        {
      type:'autogenerated',
      dirName:'Aplicaciones/Nuevo equipo',
    },
    ],
    },
  ],

    informacionGeneralSidebar: [
    
   {
      type: 'category',
      label: 'Tableau',
      collapsible:true,
      items:[
        {
      type:'autogenerated',
      dirName:'Aplicaciones/Informacion General',
    },
    ],
    },
  ],
   
=======
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
>>>>>>> 4bfef3160ef04643058a5ba9a73fe89ef9467790
};

export default sidebars;
